alpstable/gidari

README.md
=> Add Configuration Table

cmd/gidari.go
=> remove encoders

README.md
=> update note for NoSQL

.github/workflows/codeql.yml, .github/workflows/dependency-review.yml, internal/transport/transport.go
=> Add security workflows

internal/storage/mongo.go, internal/storage/postgres.go
=> Add write mutexes to storage upsert

internal/storage/mongo.go
=> Prevent concurrent Mongo Txn commits

internal/storage/mongo.go, internal/transport/transport.go
This adds a retry to the transaction commits when the server returns a 112 (WriteConflict), which appears to be the [best practice recommendation](https://www.mongodb.com/community/forums/t/recommended-way-to-handle-write-conflicts-inside-transactions/104491/3).
=> add write config retry limit for MDB

internal/web/client_test.go
=> Add integration tests for the basic round trip

cmd/gidari.go, gidari.go
=> ref: extract transport section to methods WIP

internal/web/client_test.go
=> Add integration tests for the Auth2 round trip

internal/transport/transport_test.go
#204 @prestonvasquez  I have added the required functionality now , can you check if it is working as expected. let me know if further changes are required or if it's not working as expected.
=> cleanup and upsert verfication added to the transport tests

docs/CONTRIBUTING.md, go.mod, internal/storage/postgres_test.go
Resolves #132 
- Added tests for isPk method by mocking the required framework
=> Create unit tests for postgres helpers

LICENSE, NOTICE
Restore Apache license format and add NOTICE file
Addresses #218
=> fix: Apache license format

.golangci.yml, internal/storage/postgres_test.go
- Extended the unit tests to test the helper method - `upsertStmt`
Fixes #222
=> Add test for pgmeta.upsertStmt

tools/http_message.go, tools/http_message_test.go
=> Add tests for tools.HTTPMessage

internal/storage/mongo.go, internal/storage/storage_test.go
=> add security to concurrent storage tests

.gitignore, Makefile, cmd/gidari/cmd/root.go, cmd/gidari/main.go
=> Revert "simplify cli architecture"

Makefile, README.md
=> add cli back

.gitignore, cmd/gidari/cmd.go
=> remove gidari from ignore

README.md
Closes issue #264 
Go get command added!
:)
=> Closes issue #264 | Go get command added under installation/library section

gidari.go
=> NewConfig routine code copied.

scripts/fmt.sh
=> Update fmt.sh to check for binary.

README.md
=> clean up raw url

README.md
=> remove the repository section of the README.md

docs/resources.md
=> remove resources doc

README.md, docs/release_process.md
=> add release notes

config/rate_limit_config_test.go
Resolves #297 
Please let me know if there are more cases you'd like tested. The```config.validate``` function seemed fairly straight forward, so I included some test cases that seemed obvious.
=> Add validate test

README.md
I have added table of contents in the readme file. Please review and merge my pull request
Resolves #320
=> Added index of contents in README.md

internal/transport/transport.go, internal/transport/transport_test.go
=> Unit tests for transport.newFetchConfig

.github/workflows/ci.yml, Makefile, internal/repository/example_test.go
=> Add integration test for repository package

docs/CONTRIBUTING.md
=> docs: add protoc windows installation to contributing.md #329

README.md, internal/mongo/mongo.go, internal/mongo/mongo_integration_test.go, internal/postgres/postgres.go, internal/postgres/postgres_integration_test.go, internal/proto/storage.go, internal/proto/test_runner.go
=> Add ping method to Storage interface

.gitignore, internal/transport/transport_test.go
=> Add Unit Test for transport.flattenConfigRequest

internal/mongo/mongo_integration_test.go, internal/postgres/postgres_integration_test.go, internal/proto/test_runner.go
Resolves #309. Thanks @prestonvasquez for the guidance!
=> Finish close db

cmd/gidari/cmd.go
=> giving verbose command the -v flag

internal/mongo/mongo_integration_test.go, internal/postgres/postgres_integration_test.go, internal/proto/test_runner.go
Resolves <#293
Due to some reasons I couldn't test the code , kindly let me know if any changes are required.
=> Add truncate method to proto.TestRunner

docs/release_process.md
=> update the release process

.golangci.yml
PoC on linter issue. Will close afterward.
Resolves #364
=> Comment on exported

gidari_example_test.go, http.go, http_test.go, mock_test.go, proto/decode.go, proto/decode_test.go, proto/storage.go, service.go
=> alpstable#373 add list writer

README.md
=> alpstable#377 update README.md storage adapters

go.mod, go.sum
=> alpstable#352 remove the sync dependency

NOTICE, decode.go, decode_test.go, gidari_example_test.go, http.go, http_test.go, mock_test.go, scripts/add-license.sh, service.go, third_party/accept/accept.go, third_party/accept/accept_test.go, version/version.go
=> alpstable#382 update license information

gidari_example_test.go
=> alpstable#363 support Iterator.Next()

examples/csvpb/go.mod, examples/csvpb/go.sum, examples/csvpb/main.go
Update the examples version for csvpb
=> update the csvpb version

version.go
=> moving version.go to root directory

http.go, service.go
=> alpstable#402 skip nil options on request constructor

auth/auth.go, decode.go, http.go
Resolves #399 
Please advise if not whats expected.
=> Check http status

.golangci.yml, README.md, decode.go, decode_test.go, examples/websocket/go.mod, examples/websocket/go.sum, examples/websocket/main.go, http.go, mock_test.go, service.go, socket.go, socket_test.go
=> Alpstable#411 Implement Network Socket Support

.github/workflows/ci.yml, auth/auth.go, auth/auth_test.go, gidari_example_test.go
=> alpstable#416 support kraken authentication
